---
- name: Security - Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Security - Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
