---
- name: Common - Enable swap
  ansible.builtin.shell: mkswap /swapfile && swapon /swapfile
  changed_when: true

- name: Common - Persist swap in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile none swap sw 0 0"
    state: present
  listen: Common - Enable swap
