---
- name: Deploy - Restart docker compose
  ansible.builtin.command:
    cmd: docker compose restart
    chdir: "{{ deploy_dir }}"
  become: true
  become_user: "{{ deploy_user }}"
  changed_when: true
